### ISSUE TITLE
Tool Stabilizer

### ISSUE THREAD

**Issue by dezminator** [openfab-lab/chic2.0#1]
We have still to find a way to keep the tool suspended and test if the weight of the tool is not hindering the use of the pantograph. 
Maybe add a parallel arm to keep the tool straightened up.

**Comment by nicolasdb** [comment]
this was not a problem during the last workshop. 

- the flexible is not very heavy
- the weight doesn't affect the system, the drill bit is with spirale and drag down the tool into the material.
- the new "shield" let you set the maximum depth for the drill bit.
